### ISSUE TITLE
After Using the instructions

### ISSUE THREAD

**Issue by ShubhamkumarAnand** [sudiptob2/cf-stats#37]
![Screenshot from 2022-08-23 22-06-48](https://user-images.githubusercontent.com/56271682/186213675-3fda5c84-65ae-4857-ad5a-70d598b5a73b.png)

**Comment by sudiptob2** [comment]
Hey, thanks for reporting. is it resolved ?

**Comment by ShubhamkumarAnand** [comment]
Yup, Silly Me
I had put .me in front of my cf handle name 🤣
BTW A great Open Source projects.

**Comment by sudiptob2** [comment]
Thanks, but one problem I saw, the card broke because your name is too long

**Comment by sudiptob2** [comment]
Can you report that issue? I will be working on that

**Comment by imskanand** [comment]
> Can you report that issue? I will be working on that

No There is no problem in this. because your cf handle contains .me in the end i thought it was also necessary to put mine into it but it returns the NoneObj type because of this.

**Comment by sudiptob2** [comment]
Thanks, I was talking about another problem, However, I already created issue #38 on that bug.

**Comment by ShubhamkumarAnand** [comment]
I think the mistake was from my side to put "ShubhamkumarAnand.me" which is wrong. That's why it get some errors

**Comment by sudiptob2** [comment]
No there are other problems compare to the card in my profile and your profile, your contribution section is not visible because your name is long.

**Comment by ShubhamkumarAnand** [comment]
Yes the card is not looking proper from my side.

**Comment by sudiptob2** [comment]
I have created issue #38 for that. Will fix it

**Comment by sudiptob2** [comment]
Hi @ShubhamkumarAnand issue #38 has been fixed. You can take an update. Hope it will fix your long name issue
