### ISSUE TITLE
Add video tutorial in Hindi language

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/cf-stats#48]
for general instruction ref: #47 

Look at this step-by-step screenshot guide to get an idea of how the tutorial should look like
[step-by-step screenshot](https://github.com/sudiptob2/cf-stats/blob/main/docs/INSTALLATIONSTEPS.md)

Upload the video to your youtube channel and add the link in the project readme

**Comment by harshxtanwar** [comment]
can I get assigned to this issue @sudiptob2 I would like to work on it.

**Comment by shubhankarsharma876** [comment]
> for general instruction ref: #47 
> 
> Look at this step-by-step screenshot guide to get an idea of how the tutorial should look like
> [step-by-step screenshot](https://github.com/sudiptob2/cf-stats/blob/main/docs/INSTALLATIONSTEPS.md)
> 
> Upload the video to your youtube channel and add the link in the project readme

Can you assign me with this issue?

**Comment by sudiptob2** [comment]
> can I get assigned to this issue @sudiptob2 I would like to work on it.

Shubhankarsharma876 is working on this issue. Please stay tuned for future issues

**Comment by sudiptob2** [comment]
> > for general instruction ref: #47 
> > 
> > Look at this step-by-step screenshot guide to get an idea of how the tutorial should look like
> > [step-by-step screenshot](https://github.com/sudiptob2/cf-stats/blob/main/docs/INSTALLATIONSTEPS.md)
> > 
> > Upload the video to your youtube channel and add the link in the project readme
> 
> Can you assign me with this issue?

Will assign you shortly

**Comment by shubhankarsharma876** [comment]
> > > for general instruction ref: #47
> > > Look at this step-by-step screenshot guide to get an idea of how the tutorial should look like
> > > [step-by-step screenshot](https://github.com/sudiptob2/cf-stats/blob/main/docs/INSTALLATIONSTEPS.md)
> > > Upload the video to your youtube channel and add the link in the project readme
> > 
> > 
> > Can you assign me with this issue?
> 
> Will assign you shortly

thanks with update!

**Comment by AbhishekTiwari23** [comment]
@sudiptob2 hello sir, if there is any other issue, then please let me know I also want to contribute.

**Comment by shubhankarsharma876** [comment]
Sorry for late update.
The video tutorial is created and uploaded on youtube on this link https://www.youtube.com/watch?v=SMHzbmtHLMo
Also the PR is generated with addition of link to the readme file of the project

**Comment by sudiptob2** [comment]
closed by the PR #51
